version: "3.3"

services:
  app:
    build:
      dockerfile: ./Dockerfile
    command: > 
      bash -c "python manage.py migrate && 
      python manage.py createsuperuser --email <Почта> --noinput && 
      python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    restart: always
    environment:
      - DJANGO_SUPERUSER_USERNAME=<Логин для входа в админ панель>
      - DJANGO_SUPERUSER_PASSWORD=<Пароль для входа в админ панель>
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"
    volumes:
      - ./megano/database:/app/database


