# Generated by Django 4.2.3 on 2023-07-19 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Кол-во товаров')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('fullDescription', models.TextField(blank=True, verbose_name='Полное описание')),
                ('freeDelivery', models.BooleanField(blank=True, default=True, verbose_name='Бесплатная доставка')),
                ('popular', models.BooleanField(default=False, verbose_name='Популярный')),
                ('limited', models.BooleanField(default=False, verbose_name='Лимитированный')),
                ('dateFrom', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала')),
                ('dateTo', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('salePrice', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Цена со скидкой')),
                ('sale', models.BooleanField(default=False, verbose_name='Скидка')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_category', to='category.category', verbose_name='Категория ')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Спецификация',
                'verbose_name_plural': 'Спецификации',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('rate', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='product.products')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='specification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specification', to='product.specification', verbose_name='Спецификация'),
        ),
        migrations.AddField(
            model_name='products',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='tags.tags', verbose_name='Теги'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, upload_to='products_images', verbose_name='Фотография')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.products')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображении',
            },
        ),
    ]
